### ISSUE TITLE
Format Values on Tooltips?

### ISSUE THREAD

**Issue by gegere** [Ejdamm/Chart.js-PHP#3]
Hello, great work on this PHP class to help get others up and running faster. Looking over the class and would like to pass in a callback.

Any ideas on how this could be incorporated?
https://github.com/jtblin/angular-chart.js/issues/33

**Comment by adamgeorgsson** [comment]
Hi,
This was a tough one! I found two possible solutions but honestly I don't know much of what I am doing since I don't know javascript very well.

The suggested method for callbakcs is like this
```
options: {
    tooltips: {
        callbacks: {
            label: function(tooltipItem, data){
                return "example";
            }
        }
    }
}
```
The corresponding php version would be
```
$options = array(
    'tooltips' => array(
        'callbacks' => array(
            'label' => "function(tooltipItem, data){return 'Hello world';}"
        )
    )
);
```
That will however be parsed as a string and not a function by json_encode(). So I would have to write a function that searches for the 'function' keyword and remove the quotes from the json output.

The second solution is to ignore that this is a PHP wrapper and put the callback function somewhere above loadChartJsPhp() function like this:

```
<script>
    Chart.defaults.global.tooltips.callbacks.label = function(tooltipItem, data) {
        return "hello world";
    };

    (function () {
        loadChartJsPhp();
    })();
</script>
```

**Comment by adamgeorgsson** [comment]
It should work now if you get the quotation marks right (not as how I suggested before)
```
$options = array(
    'responsive' => false,
    'tooltips' => array(
        'callbacks' => array(
            'label' => 'function(tooltipItem, data){return "Hello world";}'
        )
    )
);
```
